### ISSUE TITLE
La charte graphique

### ISSUE THREAD

**Issue by elonkask** [youcoder-ma/Thegreenfoundation#4]
créer une charte graphique

**Comment by ELBOUANANI10** [comment]
est ce que le travail est déja fais .??

**Comment by Amine-Ela** [comment]
j'ai terminé la charte graphique

**Comment by oumaimaboumarte48** [comment]
le rapport et ça marche bien

**Comment by Amine-Ela** [comment]
ok, bon travail continue

**Comment by elonkask** [comment]
Amine ????
